# Generated by Django 4.1.3 on 2022-11-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='redessociales',
            options={'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
    ]
