# Generated by Django 4.1.3 on 2022-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contacto_options_alter_redessociales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=120, verbose_name='Apellidos'),
        ),
    ]
