# Generated by Django 4.1.3 on 2022-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contacto_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'verbose_name': 'Suscriptor', 'verbose_name_plural': 'Suscriptores'},
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='publicado', verbose_name='Slug'),
        ),
    ]
