# Generated by Django 4.1.3 on 2022-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_post_options_alter_suscriptor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='fecha_publicacion', verbose_name='Slug'),
        ),
    ]
